# Generated by Django 4.2 on 2026-01-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='teacher_id',
            new_name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
    ]
