# Generated by Django 4.2 on 2026-01-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='classroomgroup',
            name='section_name',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.faculty'),
        ),
    ]
